# Generated by Django 5.2.4 on 2025-07-13 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutme',
            options={'ordering': ['order'], 'verbose_name_plural': 'About Me'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['order'], 'verbose_name_plural': 'Education'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['order'], 'verbose_name_plural': 'Skills'},
        ),
        migrations.AddField(
            model_name='aboutme',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
