# Generated by Django 5.2.4 on 2025-07-13 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_projects'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'ordering': ['order'], 'verbose_name_plural': 'Projects'},
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='gtithub_url',
            new_name='github_url',
        ),
        migrations.AddField(
            model_name='projects',
            name='image_file',
            field=models.CharField(blank=True, help_text='Image file name (e.g., expense-tracker-img.png)', max_length=200),
        ),
        migrations.AddField(
            model_name='projects',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Show this project in the main view'),
        ),
        migrations.AddField(
            model_name='projects',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='projects',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
