# Generated by Django 5.2.4 on 2025-07-13 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_projects_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='image_file',
        ),
        migrations.AddField(
            model_name='projects',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload project screenshot', null=True, upload_to='project_images/'),
        ),
    ]
